### ISSUE TITLE
sensors settings

### ISSUE THREAD

**Issue by Ak1mb00** [jhoralek/acond-heat-pump#3]
Would it be possible to share your sensor settings? I´m able to read from input registers  but i'm not able to write a holding register. 
I don't know how to set up the script: modbus.write_register for set water tank

```
alias: TUV
sequence:
  - service: modbus.write_register
    data:
      address: ????
      slave: 1
      hub: Acond
      value: "550"
mode: single
```
additional:
In Acond interfeace there is possible to set up TUV 55 °C - description for acond modbus there is only 46°C. Do you use higher then 46? Does it work?

My sensors:

````
modbus:
  - name: Acond
    type: tcp
    host: 192.168.1.9
    port: 502
    sensors:
    - name: ACOND_T_act_TUV
      slave: 1
      address: 5
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      unit_of_measurement: C
      device_class: temperature
      unique_id: 30006
    - name: ACOND_T_set_TUV
      slave: 1
      address: 4
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      unit_of_measurement: C
      device_class: temperature
      unique_id: 30005
    - name: ACOND_T_act_water_back
      slave: 1
      address: 8
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      unit_of_measurement: C
      device_class: temperature
      unique_id: 30009
    - name: ACOND_T_set_indoor1
      slave: 1
      address: 0
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      unit_of_measurement: C
      device_class: temperature
      unique_id: 30001
    - name: ACOND_T_act_indoor1
      slave: 1
      address: 1
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      unit_of_measurement: C
      device_class: temperature
      unique_id: 30002
    - name: ACOND_T_act_air
      slave: 1
      address: 9
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      unit_of_measurement: C
      device_class: temperature
      unique_id: 30010
    - name: ACOND_T_set_water_back
      slave: 1
      address: 7
      data_type: int16
      scale: 0.1
      precision: 1
      input_type: input
      unit_of_measurement: C
      device_class: temperature
      unique_id: 30008 
````
thank you for your time

**Comment by jhoralek** [comment]
Hi Martin, 
thanks for your request.

here is my modbus setup in configuration.yaml

```
modbus:
  - type: tcp
    name: TC
    host: 192.168.2.8
    port: 502
    timeout: 30
    sensors:
      - name: TC_target_temp_circle_1
        slave: 1
        address: 0
        scale: 0.1
        precision: 1
        input_type: input
        unit_of_measurement: C°
        device_class: temperature
        unique_id: 30001
      - name: TC_actual_temp_circle_1
        slave: 1
        address: 1
        scale: 0.1
        precision: 1
        input_type: input
        unit_of_measurement: C°
        device_class: temperature
        unique_id: 30002
      - name: TC_target_TUV
        slave: 1
        address: 4
        scale: 0.1
        precision: 1
        input_type: input
        unit_of_measurement: C°
        device_class: temperature
        unique_id: 30005
      - name: TC_actual_TUV
        slave: 1
        address: 5
        scale: 0.1
        precision: 1
        input_type: input
        unit_of_measurement: C°
        device_class: temperature
        unique_id: 30006
      - name: TC_state
        slave: 1
        address: 6
        input_type: input
        unique_id: 30007
      - name: TC_target_water_back
        slave: 1
        address: 7
        scale: 0.1
        precision: 1
        input_type: input
        unit_of_measurement: C°
        device_class: temperature
        unique_id: 30008
      - name: TC_actual_water_back
        slave: 1
        address: 8
        scale: 0.1
        precision: 1
        input_type: input
        unit_of_measurement: C°
        device_class: temperature
        unique_id: 30009
      - name: TC_air_temp
        slave: 1
        address: 9
        scale: 0.1
        precision: 1
        input_type: input
        unit_of_measurement: C°
        device_class: temperature
        unique_id: 30010
      - name: TC_reg_type
        slave: 1
        address: 14
        input_type: input
        unique_id: 30015
```

Well, it seems that we have almost identical sensor setup.

Here is my setup of modbus:write_regilster for TUV
```
service: modbus.write_register
data:
  address: 4
  slave: 1
  hub: TC
  value: 460
```

Target temp in first circle
```
service: modbus.write_register
data:
  address: 0
  slave: 1
  hub: TC
  value: 220
```
It looks there is little confusion with addresses. 

address 40001 response to number 0. This is because 40001 is first in array of addresses. When calling `modbus:write_register` you need to use index of the array which is 0, and it then continues in sequence.

Here is my acond web interface of ModbusTCP page
![image](https://user-images.githubusercontent.com/12426037/212349505-ffd7361f-2e61-4233-8f96-966c0dfd4b8f.png)

It looks like there is not a complete list of registries as shown in the documentation from ACOND. I'm going to contact them and ask when is possible to update firmware of the TC remotely.

Wen some mistake is made while calling write_register service, then ModbusTCP will be broken and then you need to turn your TC off and then shut down the circuit breaker. Then turn on the circuit break and TC on on the front control panel. Then ModbusTCP will be restarted and reeady to use again.

I think this project with lovelace itnerface is obsolete, and if I have a little extra time I'll get it working again.

**Comment by Ak1mb00** [comment]
Thank you very much. IT works well and the boiler can be set up to 55 as well as in the app. The reboot trick is priceless!

**Comment by Ak1mb00** [comment]
Btw: new firmware looks likes that

![Screenshot_20230113-172559~2](https://user-images.githubusercontent.com/121321795/212381700-cb520fbf-b642-4792-b320-c4ceed7a901e.png)

**Comment by jhoralek** [comment]
There is one con.

When you're control TC over motbus you need to update actual temp. value of heating circuit from outside, because all values from TC sensors are overwritten with holding registers.

I've sensors in all of my rooms. I created set of evaluation automations that adjust the value of the current temperature in TC circuit as needed.

So you need to mind on it.

JH.

**Comment by Ak1mb00** [comment]
Ok, good to know. 
Can i ask for help one last time?
how to set up a script with data from the sensor?
```
alias: Temp. first circle actual
sequence:
  - service: modbus.write_register
    data:
      address: 1
      slave: 1
      hub: Acond
      value: {{ states ('sensor.ewelink_th01_temperature')}}
mode: single
```
